[package]
name = "rs2"
version = "0.1.0"
authors = ["Denys Lytviak <denys.lytviak@embiq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
